export enum ActivityAction {
    COMPANY_REGISTERED = 'COMPANY_REGISTERED',
    CANDIDATE_REGISTERED = 'CANDIDATE_REGISTERED',
    TEST_PUBLISHED = 'TEST_PUBLISHED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
    SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
    COMPANY_APPROVED = 'COMPANY_APPROVED'
}