export enum ActivityAction {
    COMPANY_REGISTERED = 'COMPANY_REGISTERED',
    CANDIDATE_REGISTERED = 'CANDIDATE_REGISTERED',
    TEST_PUBLISHED = 'TEST_PUBLISHED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
    SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
    COMPANY_APPROVED = 'COMPANY_APPROVED',
    SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
    SUBSCRIPTION_DOWNGRADED_TO_FREE = 'SUBSCRIPTION_DOWNGRADED_TO_FREE',
    START_TRIAL = 'START_TRIAL',
}