export type NotificationChannel = 'EMAIL' | 'IN_APP'
export type TemplateFieldType = "text" | "textarea" | "number" | "dropdown" | "checkbox" | "button"
export type TemplateFieldPurpose = "SUBJECT" | "TITLE" | "BODY" | "FOOTER" | "CTA_BUTTON" | "OTP_LABEL" | "OTP_CODE" | "EXPIRY_TEXT" | "SUPPORT_TEXT" | "CUSTOM"
export type EmailLayoutType = 'COMMON'

export const TemplateStatus = {
  ACTIVATE: 'Activate',
  DEACTIVATE: 'Deactivate' // Deactivate
}

export const NotificationEvents = {
    REGISTER_OTP_REQUESTED: 'REGISTER_OTP_REQUESTED',
    COMPANY_PROFILE_UPDATED: 'COMPANY_PROFILE_UPDATED',
    COMPANY_APPROVED: 'COMPANY_APPROVED',
    COMPANY_REJECTED: 'COMPANY_REJECTED',
    RESET_PASSWORD_OTP_REQUESTED: 'RESET_PASSWORD_OTP_REQUESTED',
    SUBSCRIPTION_REMINDER: 'SUBSCRIPTION_REMINDER',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    ACCOUNT_RESTORE: 'ACCOUNT_RESTORE',  
    TEST_INVITE: 'TEST_INVITE', 
    CANCEL_TEST: 'CANCEL_TEST',
    RESCHEDULE_TEST: 'RESCHEDULE_TEST',
    TEST_REMOVED: 'TEST_REMOVED',
    TRIAL_END_REMINDER: 'TRIAL_END_REMINDER',
    CANDIDATE_SHORTLISTED: 'CANDIDATE_SHORTLISTED',
    CANDIDATE_REJECTED: 'CANDIDATE_REJECTED',
    INVITE_CANDIDATE_INTERVIEW: 'INVITE_CANDIDATE_INTERVIEW',
    INVITE_INTERVIWER: 'INVITE_INTERVIEWER',
    CANCEL_INTERVIEW_INTERVIWER: 'CANCEL_INTERVIEW_INTERVIEWER',
    CANCEL_INTERVIEW_CANDIDATE: 'CANCEL_INTERVIEW_CANDIDATE',
    RESCHEDULE_INTERVIEW: 'RESCHEDULE_INTERVIEW',
    INTERVIEW_CANDIDATE_REJECTED: 'INTERVIEW_CANDIDATE_REJECTED',
    SEND_OFFER_LETTER: 'SEND_OFFER_LETTER',
} as const

export type NotificationEvent = (typeof NotificationEvents)[keyof typeof NotificationEvents]


export const NotificationChannels = {
  EMAIL: 'EMAIL',
  IN_APP: 'IN_APP'
} as const

// export type NotificationChannel =
//   (typeof NotificationChannels)[keyof typeof NotificationChannels]