export enum TestStatus {
    DRAFT = 'DRAFT',
    PUBLISHED = 'PUBLISHED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    DELETED = 'DELETED'
}

export enum QuestionSource {
    ADMIN_LIBRARY = 'ADMIN_LIBRARY',
    COMPANY_LIBRARY = 'COMPANY_LIBRARY',
    TEST_ONLY = 'TEST_ONLY'
}

export enum CandidateTestStatus {
   DRAFT = 'DRAFT',
   VERIFIED = 'VERIFIED',
   INVITED = 'INVITED',
   IN_PROGRESS = 'IN_PROGRESS',
   SUBMITTED = 'SUBMITTED',
   EXPIRED = 'EXPIRED',
   DISQUALIFIED = 'DISQUALIFIED',
   REMOVED = 'REMOVED'
}

export enum CandidateSelectionStatus {
    PENDING = 'PENDING',
    SHORTLISTED = 'SHORTLISTED',
    REJECTED = 'REJECTED'
}

