export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
  },

  COMPANY: {
    VERIFY_EMAIL: '/company/verifyemail',
    VERIFY_OTP: '/company/verifyotp',
    FORGOT_PASSWORD: '/company/forgotpassword',
    RESET_PASSWORD: '/company/resetpassword',
    DASHBOARD: '/company/dashboard',
    SETTINGS:'/company/settings',
    PASSWORD: '/company/password',
    RESTORE: '/company/restore-account',
    JOB_ROLES: '/company/job-roles',
    QUESTIONS: '/company/questions',
    SUBSCRIPTION: '/company/subscriptions',
    TEST: '/company/tests',
    EDIT_TEST: '/company/TEST/edit/:id',
    CREATE_TEST: '/company/test/create',
    RESCHEDULE_TEST: '/company/test/reschedule/:id',
    CREATE_TEST_SUCCESS: '/company/test/success',
    CANCEL_TEST: '/company/test/:id/cancel',
    RESHEDULE_TEST: '/company/test/reschedule',
    TEST_DETAILS: '/company/test/:testId',
    INTERVIEWS: '/company/interviews',
    CANCEL_INTERVIEW: '/company/interview/:interviewId/cancel',
    RESCHEDULE_INTERVIEW: '/company/interview/:interviewId/reschedule',
    VIEW_INTERVIEW_DETAILS: '/company/interview/:interviewId',
    // COMPANY_INTERVIEW_READY: '/company/interview/:roomId/:token'
  },

  CANDIDATE: {
    VERIFY_OTP: '/candidate/verifyotp',
    FORGOT_PASSWORD: '/candidate/forgotpassword',
    RESET_PASSWORD: '/candidate/resetpassword',
    DASHBOARD: '/candidate/dashboard',
    SUBSCRIPTION: '/candidate/subscription',
    START_TEST: '/candidate/test/:token',
    TEST_LOGIN: '/candidate/test/:token/login',
    TEST_INSTRUCTIONS: '/candidate/test/instructions/:token',
    TEST_QUESTIONS: '/candidate/test/questions/:token',
    TEST_SUBMIT: '/candidate/test/submit/:token',
    TEST_TERMINATE: '/candidate/test/terminate',
    QUESTION_SUBMITTED: '/candidate/test/quesion-submitted',
    PRACTICE: '/candidate/practice/:questionId',
  },

  COMMON: {
    PAYMENT_STATUS: '/payment-status',
    PAYMENT: '/payment',
    INTERVIEW_READY: '/interview/:roomId/:token',
    INTERVIEW_COMPLETED: '/interview/:roomId/:token/completed',
    INTERVIEW_EXPIRED: '/interview/:roomId/:token/expired'
  },

  ADMIN: {
    LOGIN: '/admin/login',
    DASHBOARD: '/admin/dashboard',
    COMPANIES: '/admin/companies',
    CANDIDATES: '/admin/candidates',
    COMPANY_DETAIL: `/admin/company/:id`,
    COMPANY_DETAIL_PATH: (id: string) => `/admin/company/${id}`,
    CATEGORIES: '/admin/categories',
    QUESTIONS: '/admin/questions',
    PRACTICE_LIBRARY: '/admin/practicelibrary',
    SUBSCRIPTIONS: '/admin/subscriptions',
    SETTINGS: '/admin/settings',
  },
}